name: FER_CNN
model_name: ConvNetFer
model_args:
  input_shape:
    - 1
    - 48
    - 48
  num_classes: 7
  hidden_layers:
    - 64
    - 128
    - 64
  dropout: 0.3
  activation: nn.ReLU
  norm_layer: nn.BatchNorm2d
data_args:
  data_dir: ../dataset
  path: ../dataset/icml_face_data.csv
  batch_size: 64
  num_workers: 2
  pin_memory: true
optim_args:
  optimizer: Adam
  lr: 0.001
  weight_decay: 0.0001
scheduler_args:
  scheduler: StepLR
  step_size: 10
  gamma: 0.1
train_args:
  epochs: 50
  log_interval: 10
  seed: 42
  device: cuda
  save_path: checkpoints/fer_cnn.pth
