name: FER_resnet
model_name: ResNetFer
model_args:
  input_shape:
    - 1
    - 48
    - 48
  num_classes: 7
  
  dropout: 0.5
  activation: ReLU
  norm_layer: "BatchNorm2d"
data_args:
  data_dir: dataset
  path: dataset/icml_face_data.csv
  batch_size: 512
  num_workers: 8
  pin_memory: true
train_args:
  epochs: 150
  log_interval: 10
  seed: 42
  device: cuda:0
  save_path: checkpoints/fer_resnet.pth
  criterion: "CrossEntropyLoss"
  optim_args:
    optimizer: "Adam"
    lr: 0.001
    weight_decay: 0.00001
  scheduler_args:
    scheduler: "StepLR"
    step_size: 10
    gamma: 0.1
log_dir: log/


